### ISSUE TITLE
Move XP web services to hosted solutions

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#285]
# Scope of Change

The XP-Framework's web sites and services will move form our dedicated server to hosted solutions.
# Rationale

Less system administration work.
# Functionality
## Web site

The Website, documentation and code examples will all redirect to the GitHub project pages. We will discontinue the blog, the ChangeLog and issues, RFCs and Wiki pages linked from there will be the news.
## Build system

The XP build system can be replaced by Travis-CI's deployment.
## Downloads 

Downloads will be added to git and can then be downloaded via raw.github.com
# Security considerations
# Speed impact
# Dependencies
# Related documents

**Comment by kiesel** [comment]
## Build process

Options for hosting:
- [1&1 Virtual Server L Linux](https://hosting.1und1.de/vserver?__lf=Order-Tariff&linkId=hd.subnav.vserver) 5€/p.m.
- [Digital Ocean](https://digitalocean.com/pricing/)

Options for IaaS:
- [IronMQ](http://www.iron.io/mq) who seem to offer free MQ services and have GitHub integration
- [Amazon SQS Queue](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html)

## Downloads

via GitHub:
- [GitHub Releases](https://developer.github.com/v3/repos/releases/)
- [GitHub Downloads](https://developer.github.com/v3/repos/downloads/) - was deprecated 2012-12-11

**Comment by thekid** [comment]
http://docs.travis-ci.com/user/deployment/releases/

**Comment by thekid** [comment]
### Created with Travis-CI GitHub deployment:

https://travis-ci.org/xp-framework/core/jobs/34445138
https://github.com/xp-framework/core/releases/tag/v6.0.0alpha4

Unfortunately, the "pre-release" flag needed to be set manually and there's no way to supply the changelog or render a "nice" title.

**Comment by thekid** [comment]
After releasing [XPBuild 3.0.0alpha2](https://github.com/xp-framework/build/tree/travis), converting XP Modules to new cloud-hosted solution, typically using a `.travis.yml` like this:

``` yml
# xp-forge/measure

language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - wget 'https://github.com/xp-framework/xp-runners/releases/download/v5.0.0/setup' -O - | php
  - wget 'https://github.com/xp-framework/core/releases/download/v6.0.0alpha7/xp-rt-6.0.0alpha7.xar'
  - wget 'https://github.com/xp-forge/sequence/releases/download/v0.7.3/xp-sequence-0.7.3.xar'
  - ls -1 *.xar > boot.pth
  - echo "[runtime]" >> xp.ini
  - echo "date.timezone=Europe/Berlin" >> xp.ini

script:
  - ./unittest src/test/php

before_deploy:
  - export REL=`echo $TRAVIS_TAG | sed -e 's/^v//g'`
  - export MOD=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`
  - wget https://github.com/xp-framework/build/releases/download/v3.0.0alpha2/travis.xar
  - ./xp -cp travis.xar net.xp_framework.build.Travis . $MOD $REL
  - cat glue.json

deploy:
  provider: releases
  file:
    - xp-$MOD-$REL.xar
    - xp-$MOD-test-$REL.xar
    - glue.json
  skip_cleanup: true
  on:
    repo: $TRAVIS_REPO_SLUG
    tags: true
    all_branches: true
    php: 5.4
  api_key:
    secure: "..."
```

## TODO
- [x] https://github.com/xp-forge/sequence
- [x] https://github.com/xp-forge/measure
- [x] https://github.com/xp-forge/json
- [x] https://github.com/xp-forge/assert
- [x] https://github.com/xp-forge/mustache
- [x] https://github.com/xp-forge/inject
- [ ] https://github.com/xp-forge/handlebars
- [x] https://github.com/xp-forge/yaml
- [x] https://github.com/xp-forge/markdown
- [ ] https://github.com/xp-forge/gsa-xmlfeed
- [ ] https://github.com/xp-framework/csv
- [ ] https://github.com/xp-framework/rest
- [ ] https://github.com/xp-framework/rdbms
- [ ] https://github.com/xp-framework/webservices
- [ ] https://github.com/xp-framework/scriptlet
- [ ] https://github.com/xp-framework/zip
- [ ] https://github.com/xp-framework/ldap
- [ ] https://github.com/xp-framework/parser
- [ ] https://github.com/xp-framework/xml
- [ ] https://github.com/xp-framework/remote
- [ ] https://github.com/xp-framework/imaging
- [ ] https://github.com/xp-framework/http
- [ ] https://github.com/xp-framework/ftp
- [ ] https://github.com/xp-framework/mail
- [ ] https://github.com/xp-framework/core (_partially done, uses shell-based build_)

**Comment by thekid** [comment]
Revamped: Now using packagist / Composer like the rest of the PHP world.
